/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DeckRouteImport } from './routes/deck'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ReadingRouteImport } from './routes/reading'
import { Route as ApiCardVideoRouteImport } from './routes/api/card-video'
import { Route as ApiWeaveRouteImport } from './routes/api/weave'
import { Route as CardNumberRouteImport } from './routes/card.$number'
import { Route as StudioIndexRouteImport } from './routes/studio.index'
import { Route as StudioNumberRouteImport } from './routes/studio.$number'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckRoute = DeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingRoute = ReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCardVideoRoute = ApiCardVideoRouteImport.update({
  id: '/api/card-video',
  path: '/api/card-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeaveRoute = ApiWeaveRouteImport.update({
  id: '/api/weave',
  path: '/api/weave',
  getParentRoute: () => rootRouteImport,
} as any)
const CardNumberRoute = CardNumberRouteImport.update({
  id: '/card/$number',
  path: '/card/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioNumberRoute = StudioNumberRouteImport.update({
  id: '/studio/$number',
  path: '/studio/$number',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/deck': typeof DeckRoute
  '/journal': typeof JournalRoute
  '/reading': typeof ReadingRoute
  '/api/card-video': typeof ApiCardVideoRoute
  '/api/weave': typeof ApiWeaveRoute
  '/card/$number': typeof CardNumberRoute
  '/studio/$number': typeof StudioNumberRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/deck': typeof DeckRoute
  '/journal': typeof JournalRoute
  '/reading': typeof ReadingRoute
  '/api/card-video': typeof ApiCardVideoRoute
  '/api/weave': typeof ApiWeaveRoute
  '/card/$number': typeof CardNumberRoute
  '/studio/$number': typeof StudioNumberRoute
  '/studio': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/deck': typeof DeckRoute
  '/journal': typeof JournalRoute
  '/reading': typeof ReadingRoute
  '/api/card-video': typeof ApiCardVideoRoute
  '/api/weave': typeof ApiWeaveRoute
  '/card/$number': typeof CardNumberRoute
  '/studio/$number': typeof StudioNumberRoute
  '/studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/deck'
    | '/journal'
    | '/reading'
    | '/api/card-video'
    | '/api/weave'
    | '/card/$number'
    | '/studio/$number'
    | '/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/deck'
    | '/journal'
    | '/reading'
    | '/api/card-video'
    | '/api/weave'
    | '/card/$number'
    | '/studio/$number'
    | '/studio'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/deck'
    | '/journal'
    | '/reading'
    | '/api/card-video'
    | '/api/weave'
    | '/card/$number'
    | '/studio/$number'
    | '/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DeckRoute: typeof DeckRoute
  JournalRoute: typeof JournalRoute
  ReadingRoute: typeof ReadingRoute
  ApiCardVideoRoute: typeof ApiCardVideoRoute
  ApiWeaveRoute: typeof ApiWeaveRoute
  CardNumberRoute: typeof CardNumberRoute
  StudioNumberRoute: typeof StudioNumberRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck': {
      id: '/deck'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof DeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading': {
      id: '/reading'
      path: '/reading'
      fullPath: '/reading'
      preLoaderRoute: typeof ReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/card-video': {
      id: '/api/card-video'
      path: '/api/card-video'
      fullPath: '/api/card-video'
      preLoaderRoute: typeof ApiCardVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weave': {
      id: '/api/weave'
      path: '/api/weave'
      fullPath: '/api/weave'
      preLoaderRoute: typeof ApiWeaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$number': {
      id: '/card/$number'
      path: '/card/$number'
      fullPath: '/card/$number'
      preLoaderRoute: typeof CardNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$number': {
      id: '/studio/$number'
      path: '/studio/$number'
      fullPath: '/studio/$number'
      preLoaderRoute: typeof StudioNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DeckRoute: DeckRoute,
  JournalRoute: JournalRoute,
  ReadingRoute: ReadingRoute,
  ApiCardVideoRoute: ApiCardVideoRoute,
  ApiWeaveRoute: ApiWeaveRoute,
  CardNumberRoute: CardNumberRoute,
  StudioNumberRoute: StudioNumberRoute,
  StudioIndexRoute: StudioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
